/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poultry.management.system;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import static javax.swing.SwingUtilities.invokeLater;
import javax.swing.table.DefaultTableModel;
import static poultry.management.system.Connect.ConnectDB;
import static poultry.management.system.Connect.con;
import static poultry.management.system.Connect.pst;
import static poultry.management.system.Connect.rs;
import static poultry.management.system.Global.addSale;
import static poultry.management.system.Global.formatDate;
import static poultry.management.system.Global.formatDate2;
import static poultry.management.system.Global.getData;
import static poultry.management.system.Global.getItem;
import static poultry.management.system.Global.getTableData;
import static poultry.management.system.Global.saveData;
import static poultry.management.system.MainForm.mainRootPane;

/**
 *
 * @author rahman
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    String sqlS="select ID ,DATE_ ,CUSTOMER ,GROSS ,DISCOUNT ,PERCENT ,NET  from sales order by ID DESC LIMIT 200 ",
            sqlC="select NAME || '  # ' || PHONE as CUSTOMER from customers  order by ID DESC LIMIT 200 ",
            sqlItems=" select DESCRIPTION from stocks ",
            sqlAllItems=" select DESCRIPTION ,QUANTITY , RATE from stocks ",
            customer_id="",
            description="";
    
    int totalQty=0;
    Double rate=0.00;
    
    HashMap<String,Object[]> stocksCache=new HashMap<>();
    
    public Sales() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);   
        this.setAlwaysOnTop(false);
    }

    void showSales(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        getData(sqlC,cmbCustomers1,"CUSTOMER");
        getTableData(sqlS,tableSales);
        getTableData(sqlAllItems,tableItems);
        getData(sqlItems,cmbItems_S,"DESCRIPTION");
        sum();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSales = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblSum = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        cmbCustomers1 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        cmbCustomers2 = new javax.swing.JComboBox();
        jLabel84 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        dateFrom = new org.jdesktop.swingx.JXDatePicker();
        dateTo = new org.jdesktop.swingx.JXDatePicker();
        jLabel98 = new javax.swing.JLabel();
        cmbItems_S = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        lblGross = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        txtPercent = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        lblNet = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        btnRemove1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtQty = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        lblAmount = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sales");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));

        jPanel5.setBackground(new java.awt.Color(247, 247, 247));

        tableSales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE", "CUSTOMER", "GROSS", "DISCOUNT", "%", "NET"
            }
        ));
        tableSales.setEditingColumn(0);
        tableSales.setEditingRow(0);
        jScrollPane4.setViewportView(tableSales);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        pay.setText("Add Payment");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jButton4.setText("Sales Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblSum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblSum.setText("0.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(pay)
                        .addGap(18, 18, 18)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnView)
                        .addComponent(pay)
                        .addComponent(jButton4))
                    .addComponent(lblSum))
                .addGap(11, 11, 11))
        );

        jPanel8.setBackground(new java.awt.Color(247, 247, 247));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Customer"));

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel81.setText("Customer");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbCustomers1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(cmbCustomers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(247, 247, 247));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel83.setText("Customer");

        cmbCustomers2.setEditable(true);
        cmbCustomers2.setModel(cmbCustomers1.getModel());
        cmbCustomers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomers2ActionPerformed(evt);
            }
        });
        cmbCustomers2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbCustomers2KeyReleased(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel84.setText("Item");

        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel97.setText("Date : From");

        dateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateToActionPerformed(evt);
            }
        });

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel98.setText("To");

        cmbItems_S.setEditable(true);
        cmbItems_S.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cmbItems_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItems_SActionPerformed(evt);
            }
        });
        cmbItems_S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbItems_SKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel97)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel98)
                        .addGap(18, 18, 18)
                        .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCustomers2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbItems_S, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(cmbCustomers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84)
                    .addComponent(cmbItems_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel97)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel98))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));

        jPanel7.setBackground(new java.awt.Color(247, 247, 247));

        jPanel9.setBackground(new java.awt.Color(247, 247, 247));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel89.setText("Discount");

        lblGross.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGross.setText("0.00");

        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel91.setText("Net Total");

        txtPercent.setEditable(false);
        txtPercent.setText("0");

        jLabel92.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel92.setText("%");

        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel93.setText("Gross Total");

        lblNet.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNet.setText("0.00");

        txtDiscount.setText("0");
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });

        jButton1.setText("Check Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tableCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Qty", "Rate", "Amount"
            }
        ));
        tableCart.setEditingColumn(0);
        tableCart.setEditingRow(0);
        jScrollPane5.setViewportView(tableCart);

        btnRemove1.setBackground(new java.awt.Color(255, 102, 102));
        btnRemove1.setText("Remove Item");
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(txtDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel92)
                                        .addGap(12, 12, 12))
                                    .addComponent(lblGross, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(0, 136, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove1)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGross)
                    .addComponent(jLabel93))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(txtPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel92)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(lblNet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(247, 247, 247));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel87.setText("Qty");

        jLabel95.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel95.setText("Amount");

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Add to Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Quantity", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItems.setColumnSelectionAllowed(true);
        tableItems.getTableHeader().setReorderingAllowed(false);
        tableItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableItemsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableItems);
        tableItems.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        lblAmount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(0, 153, 51));
        lblAmount.setText(" ");

        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel96.setText("Description");

        lblDes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDes.setForeground(new java.awt.Color(0, 153, 0));
        lblDes.setText(" ");

        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel99.setText("Rate");

        lblRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRate.setForeground(new java.awt.Color(0, 153, 0));
        lblRate.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel99)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel95)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQty)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel96)
                        .addComponent(lblDes))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel87)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel95)
                        .addComponent(lblAmount)
                        .addComponent(jLabel99)
                        .addComponent(lblRate)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        // TODO add your handling code here:
        try{
            Double qty= Double.parseDouble(txtQty.getText());
            if(qty>totalQty){ 
                JOptionPane.showMessageDialog(this, "Quantity available is less than what you entered. \n Please enter again."); 
                lblAmount.setText("");
                txtQty.setText("");
                return;
            }
            Double amt= rate  * qty;
            lblAmount.setText( String.format("%.2f", amt) );
           // System.out.print(amt);
        }catch(Exception er){
            lblAmount.setText("");
        }
    }//GEN-LAST:event_txtQtyKeyReleased

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int i=tableSales.getSelectedRow();
         if(i<0)return;
            String id=tableSales.getValueAt(i, 0).toString();
          new Invoice(id).setVisible(true);
          
    }//GEN-LAST:event_btnViewActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       addToCart();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        int i=tableSales.getSelectedRow();
         if(i<0)return;
            String id=tableSales.getValueAt(i, 0).toString();
        new Payment(id).setVisible(true);
    }//GEN-LAST:event_payActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Report(tableSales,new String[]{"Sales Report","","",lblSum.getText()});
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateToActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_dateToActionPerformed

    private void cmbCustomers2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCustomers2KeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cmbCustomers2KeyReleased

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
        removeFromCart();
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        doSales();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased
        // TODO add your handling code here:
        calculateDiscount();
    }//GEN-LAST:event_txtDiscountKeyReleased

    private void tableItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItemsMouseClicked
        // TODO add your handling code here:
       int i= tableItems.getSelectedRow();
       String des=tableItems.getValueAt(i, 0).toString();
       lblDes.setText(des);
       
       totalQty=Integer.parseInt(tableItems.getValueAt(i, 1).toString());
       lblRate.setText(tableItems.getValueAt(i, 2).toString());
       rate= Double.parseDouble(tableItems.getValueAt(i, 2).toString());   
       
    }//GEN-LAST:event_tableItemsMouseClicked

    private void cmbCustomers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomers2ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cmbCustomers2ActionPerformed

    private void cmbItems_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItems_SActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cmbItems_SActionPerformed

    private void cmbItems_SKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbItems_SKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cmbItems_SKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }
    
    void addToCart(){
         if(rate==0 ||  txtQty.getText().isEmpty() || lblAmount.getText().isEmpty()  ){
            JOptionPane.showMessageDialog(this, "Please select Item and enter Quantity");return;
        };
        String item=lblDes.getText(),
              qty=txtQty.getText(),
              amount=lblAmount.getText();
       DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
       model.addRow(new Object[]{item,qty,rate,amount});
       
       //update quantity
       updateQty(0,item,qty);
       
       lblDes.setText("");
       txtQty.setText("");
       lblAmount.setText("");
       lblRate.setText("");
       
       totalQty=0;
       rate=0.00;
       
       calculateNet();
       getTableData(sqlAllItems,tableItems);
    }
    
    void removeFromCart(){
          int   r= tableCart.getSelectedRowCount();
        DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
        for(int i=0;i<r ;i++){
            int ii=tableCart.getSelectedRow();
           //update quantity to previous 
            String des=model.getValueAt(ii, 0).toString(),
                    qty=model.getValueAt(ii, 1).toString();
            updateQty(1,des,qty);
            model.removeRow(ii);    
        }
        
        getTableData(sqlAllItems,tableItems);
        calculateNet();
    }
    
   void updateQty(int i, String des,String qty){
       String sql="update stocks set quantity =( select quantity - ? where description =? ) where description=? ";        
       if(i==1){
           sql="update stocks set quantity= ( select quantity + ? where description =? )   where description =? ";
       }
       saveData(sql,new String[]{qty,des,des});
    }
   
   void doSales(){
       if(tableCart.getRowCount()<1)return;

        addSale(cmbCustomers1,lblGross,txtDiscount,txtPercent,lblNet,tableCart);
        clear();
        getTableData(sqlS,tableSales);
        sum();
   
   }
  
    
 
    void clear(){
        clear(0);
    }
    
   void clear(int c){
       int  i=0, r= tableCart.getRowCount();
         DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
         while(r>0 ){
             r--;
             //update quantity
             if(c==1){
                 updateQty(1,model.getValueAt(r, 0).toString(),  model.getValueAt(r, 1).toString());
             }
             model.removeRow(r);    
         }
         
        lblGross.setText("0.00");
        txtDiscount.setText("0.00");
        txtPercent.setText("0");
        lblNet.setText("");
        
        getTableData(sqlAllItems,tableItems);
   }
    
    
    public  void calculateNet(){
       if(txtDiscount.getText().isEmpty()){txtDiscount.setText("0");txtPercent.setText("0.00");};
        
       int c= tableCart.getRowCount();
       Double gross=0.00,net=0.00 , discount=0.00,percent=0.00;
       int total=0;
      
       for(int i=0;i<c;i++){
           gross+= Double.parseDouble(tableCart.getValueAt(i,3).toString() );    
       }
       net= gross - Double.parseDouble( txtDiscount.getText() );
       lblGross.setText(String.format("%.2f",gross) );
       lblNet.setText(String.format("%.2f",net) );   
    }
    
     public  void calculateDiscount(){
        try{
            if(txtDiscount.getText().isEmpty())return;
            Double discount=0.00,gross=0.00,net=0.00, percent=0.00;
       
           gross=Double.parseDouble(lblGross.getText());
           discount=Double.parseDouble(txtDiscount.getText());
           net= Double.parseDouble(lblGross.getText()) - discount ;

           lblNet.setText(String.format("%.2f",net) );

           percent =(  discount / gross * 100 );
          txtPercent.setText(String.format("%.2f",percent) ); 
        
        }catch(Exception err){
        
        }
        
    }
    
     public void search(){
         String sql=//"select ID ,DATE_ ,CUSTOMER ,GROSS ,DISCOUNT ,PERCENT ,NET from sales where 1 ",
                 "select sales.ID,sales.DATE_ ,sales.CUSTOMER ,sales.GROSS,sales.DISCOUNT , sales.PERCENT  ,sales.NET from sales join sale_items on sales.ID= sale_items.SALE_ID where 1 ", 
                 order=" order by sales.ID DESC limit 200 ";
          HashMap<String,String>  param=new HashMap<>();
         try{
             if(cmbCustomers2.getSelectedItem().toString().length()>0){
                 sql+=" and  sales.CUSTOMER like '%' || ? || '%' ";
                 param.put("Customer",cmbCustomers2.getSelectedItem().toString() );
             }
            
             if(cmbItems_S.getSelectedItem().toString().length()>0){
                 sql+=" and  sale_items.DESCRIPTION like '%' || ? || '%' ";
                 param.put("Customer",cmbItems_S.getSelectedItem().toString() );
             }
             
             if(dateFrom.getDate().toString().length()>0 && dateTo.getDate().toString().length()>0){
                 String dateF=formatDate(dateFrom.getDate().toInstant().toString());
                 String dateT=formatDate2(dateTo.getDate().toInstant().toString());
                 sql+=" and sales.DATE_  between '"+dateF+"'  and '"+dateT+"' ";
             }
             
         }catch(Exception err){System.out.print(err);}
         sql+=order;
         getTableData(sql,param,tableSales);
         sum();
     }
    
     public void sum(){
       int c=  tableSales.getRowCount();
       Double t=0.00;
       for(int i=0;i<c;i++){
           t+=Double.parseDouble(tableSales.getValueAt(i, 6).toString()); 
       }
       lblSum.setText(String.format("%.2f",t ));
     }

     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove1;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox cmbCustomers1;
    private javax.swing.JComboBox cmbCustomers2;
    private javax.swing.JComboBox cmbItems_S;
    public org.jdesktop.swingx.JXDatePicker dateFrom;
    public org.jdesktop.swingx.JXDatePicker dateTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblGross;
    private javax.swing.JLabel lblNet;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblSum;
    private javax.swing.JButton pay;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tableItems;
    private javax.swing.JTable tableSales;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtPercent;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
